services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: weight-management-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    stdin_open: true
    tty: true
    restart: unless-stopped

  # 本番用設定（コメントアウト）
  # app-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: runner
  #   container_name: weight-management-app-prod
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   env_file:
  #     - .env.local
  #   restart: unless-stopped